### ISSUE TITLE
Home Page (Guest Mode)

### ISSUE THREAD

**Issue by psatyadarma** [PINUSTECH-2022/pinus-study-frontend#25]

**Comment by AudreyFelicio** [comment]
![image](https://user-images.githubusercontent.com/54733401/214310865-854da768-8d71-4496-bfd8-5d8a87d448d5.png)

![image](https://user-images.githubusercontent.com/54733401/214310930-42e9250d-f376-4d49-9725-329ff1e33ed2.png)
